[project]
name = "quantum-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "qiskit",
    "qiskit-ibm-runtime",
    "qiskit_serverless"
]
